// Demi Lovato song list and album mappings
// Album names match the image files in Supabase albums bucket (e.g., "DWTD.jpg")

export const demiSongs = [
  // Don't Forget (2008)
  "Believe In Me",
  "Don't Forget",
  "Get Back",
  "Gonna Get Caught",
  "La La Land",
  "On the Line",
  "Party",
  "The Middle",
  "Trainwreck",
  "Two Worlds Collide",
  "Until You're Mine",
  
  // Here We Go Again (2009)
  "Catch Me",
  "Every Time You Lie",
  "Everything You're Not",
  "Falling Over Me",
  "Gift of a Friend",
  "Got Dynamite",
  "Here We Go Again",
  "Quiet",
  "Remember December",
  "So Far So Great",
  "Solo",
  "Stop The World",
  "U Got Nothin' On Me",
  "World Of Chances",
  
  // Unbroken (2011)
  "All Night Long",
  "Fix a Heart",
  "For the Love of a Daughter",
  "Give Your Heart a Break",
  "Hold Up",
  "In Real Life",
  "Lightweight",
  "Mistake",
  "My Love Is Like a Star",
  "Skyscraper",
  "Together",
  "Unbroken",
  "Who's That Boy",
  "You're My Only Shorty",
  
  // Demi (2013)
  "Something That We're Not",
  "Fire Starter",
  "Heart Attack",
  "I Hate You, Don't Leave Me",
  "In Case",
  "Made In The USA",
  "Neon Lights",
  "Never Been Hurt",
  "Nightingale",
  "Really Don't Care",
  "Shouldn't Come Back",
  "Two Pieces",
  "Warrior",
  "Without The Love",
  
  // Confident (2015)
  "Confident",
  "Cool for the Summer",
  "Father",
  "For You",
  "Kingdom Come",
  "Lionheart",
  "Mr. Hughes",
  "Old Ways",
  "Stars",
  "Stone Cold",
  "Waitin for You",
  "Wildfire",
  "Yes",
  
  // Tell Me You Love Me (2017)
  "Concentrate",
  "Cry Baby",
  "Daddy Issues",
  "Games",
  "Hitchhiker",
  "Instruction",
  "Lonely",
  "Only Forever",
  "Ready For Ya",
  "Ruin The Friendship",
  "Sexy Dirty Love",
  "Smoke & Mirrors",
  "Sober",
  "Sorry Not Sorry",
  "Tell Me You Love Me",
  "You Don't Do It For Me Anymore",
  
  // Dancing With The Devil... The Art Of Starting Over (2021) - DWTD
  "15 Minutes",
  "Anyone",
  "Butterfly",
  "California Sober",
  "Carefully",
  "Dancing With The Devil",
  "Easy",
  "Good Place",
  "I Love Me",
  "I'm Ready",
  "ICU",
  "Intro",
  "Lonely People",
  "Mad World",
  "Melon Cake",
  "Met Him Last Night",
  "My Girlfriends Are My Boyfriend",
  "OK Not To Be OK",
  "Sunset",
  "The Art Of Starting Over",
  "The Kind Of Lover I Am",
  "The Way You Don't Look At Me",
  "What Other People Say",
  
  // HOLY FVCK (2022)
  "29",
  "4 EVER 4 ME",
  "BONES",
  "CITY OF ANGELS",
  "COME TOGETHER",
  "DEAD FRIENDS",
  "EAT ME",
  "FEED",
  "FREAK",
  "HAPPY ENDING",
  "HEAVEN",
  "HELP ME",
  "SKIN OF MY TEETH",
  "SUBSTANCE",
  "WASTED",
  
  // I'm In The Dark (2023) - INTD
  "Before I Knew You",
  "Fast",
  "Frequency",
  "Ghost",
  "Here All Night",
  "In My Head",
  "Joshua Tree",
  "Kiss",
  "Let You Go",
  "Little Bit",
  "Say It",
  "Sorry To Myself"
];

// Album mapping for Demi Lovato songs
// Image files in Supabase: Dont Forget.jpg, Here We Go Again.jpg, Unbroken.jpg, Demi.jpg, Confident.jpg, TMYLM.jpg, DWTD.jpg, HOLY FVCK.jpg, INTD.jpg
export const demiAlbumMap = {
  // Don't Forget (2008)
  "Believe In Me": "Dont Forget",
  "Don't Forget": "Dont Forget",
  "Get Back": "Dont Forget",
  "Gonna Get Caught": "Dont Forget",
  "La La Land": "Dont Forget",
  "On the Line": "Dont Forget",
  "Party": "Dont Forget",
  "The Middle": "Dont Forget",
  "Trainwreck": "Dont Forget",
  "Two Worlds Collide": "Dont Forget",
  "Until You're Mine": "Dont Forget",
  
  // Here We Go Again (2009)
  "Catch Me": "Here We Go Again",
  "Every Time You Lie": "Here We Go Again",
  "Everything You're Not": "Here We Go Again",
  "Falling Over Me": "Here We Go Again",
  "Gift of a Friend": "Here We Go Again",
  "Got Dynamite": "Here We Go Again",
  "Here We Go Again": "Here We Go Again",
  "Quiet": "Here We Go Again",
  "Remember December": "Here We Go Again",
  "So Far So Great": "Here We Go Again",
  "Solo": "Here We Go Again",
  "Stop The World": "Here We Go Again",
  "U Got Nothin' On Me": "Here We Go Again",
  "World Of Chances": "Here We Go Again",
  
  // Unbroken (2011)
  "All Night Long": "Unbroken",
  "Fix a Heart": "Unbroken",
  "For the Love of a Daughter": "Unbroken",
  "Give Your Heart a Break": "Unbroken",
  "Hold Up": "Unbroken",
  "In Real Life": "Unbroken",
  "Lightweight": "Unbroken",
  "Mistake": "Unbroken",
  "My Love Is Like a Star": "Unbroken",
  "Skyscraper": "Unbroken",
  "Together": "Unbroken",
  "Unbroken": "Unbroken",
  "Who's That Boy": "Unbroken",
  "You're My Only Shorty": "Unbroken",
  
  // Demi (2013)
  "Something That We're Not": "Demi",
  "Fire Starter": "Demi",
  "Heart Attack": "Demi",
  "I Hate You, Don't Leave Me": "Demi",
  "In Case": "Demi",
  "Made In The USA": "Demi",
  "Neon Lights": "Demi",
  "Never Been Hurt": "Demi",
  "Nightingale": "Demi",
  "Really Don't Care": "Demi",
  "Shouldn't Come Back": "Demi",
  "Two Pieces": "Demi",
  "Warrior": "Demi",
  "Without The Love": "Demi",
  
  // Confident (2015)
  "Confident": "Confident",
  "Cool for the Summer": "Confident",
  "Father": "Confident",
  "For You": "Confident",
  "Kingdom Come": "Confident",
  "Lionheart": "Confident",
  "Mr. Hughes": "Confident",
  "Old Ways": "Confident",
  "Stars": "Confident",
  "Stone Cold": "Confident",
  "Waitin for You": "Confident",
  "Wildfire": "Confident",
  "Yes": "Confident",
  
  // Tell Me You Love Me (2017)
  "Concentrate": "TMYLM",
  "Cry Baby": "TMYLM",
  "Daddy Issues": "TMYLM",
  "Games": "TMYLM",
  "Hitchhiker": "TMYLM",
  "Instruction": "TMYLM",
  "Lonely": "TMYLM",
  "Only Forever": "TMYLM",
  "Ready For Ya": "TMYLM",
  "Ruin The Friendship": "TMYLM",
  "Sexy Dirty Love": "TMYLM",
  "Smoke & Mirrors": "TMYLM",
  "Sober": "TMYLM",
  "Sorry Not Sorry": "TMYLM",
  "Tell Me You Love Me": "TMYLM",
  "You Don't Do It For Me Anymore": "TMYLM",
  
  // Dancing With The Devil... The Art Of Starting Over (2021)
  "15 Minutes": "DWTD",
  "Anyone": "DWTD",
  "Butterfly": "DWTD",
  "California Sober": "DWTD",
  "Carefully": "DWTD",
  "Dancing With The Devil": "DWTD",
  "Easy": "DWTD",
  "Good Place": "DWTD",
  "I Love Me": "DWTD",
  "I'm Ready": "DWTD",
  "ICU": "DWTD",
  "Intro": "DWTD",
  "Lonely People": "DWTD",
  "Mad World": "DWTD",
  "Melon Cake": "DWTD",
  "Met Him Last Night": "DWTD",
  "My Girlfriends Are My Boyfriend": "DWTD",
  "OK Not To Be OK": "DWTD",
  "Sunset": "DWTD",
  "The Art Of Starting Over": "DWTD",
  "The Kind Of Lover I Am": "DWTD",
  "The Way You Don't Look At Me": "DWTD",
  "What Other People Say": "DWTD",
  
  // HOLY FVCK (2022)
  "29": "HOLY FVCK",
  "4 EVER 4 ME": "HOLY FVCK",
  "BONES": "HOLY FVCK",
  "CITY OF ANGELS": "HOLY FVCK",
  "COME TOGETHER": "HOLY FVCK",
  "DEAD FRIENDS": "HOLY FVCK",
  "EAT ME": "HOLY FVCK",
  "FEED": "HOLY FVCK",
  "FREAK": "HOLY FVCK",
  "HAPPY ENDING": "HOLY FVCK",
  "HEAVEN": "HOLY FVCK",
  "HELP ME": "HOLY FVCK",
  "SKIN OF MY TEETH": "HOLY FVCK",
  "SUBSTANCE": "HOLY FVCK",
  "WASTED": "HOLY FVCK",
  
  // I'm In The Dark (2023)
  "Before I Knew You": "INTD",
  "Fast": "INTD",
  "Frequency": "INTD",
  "Ghost": "INTD",
  "Here All Night": "INTD",
  "In My Head": "INTD",
  "Joshua Tree": "INTD",
  "Kiss": "INTD",
  "Let You Go": "INTD",
  "Little Bit": "INTD",
  "Say It": "INTD",
  "Sorry To Myself": "INTD"
};
