// Demi Lovato song list and album mappings
// Album names match the image files in Supabase albums bucket (e.g., "DWTD.jpg")

export const demiSongs = [
  // Don't Forget (2008)
  "Believe In Me",
  "Don't Forget",
  "Get Back",
  "Gonna Get Caught",
  "La La Land",
  "On the Line",
  "Party",
  "The Middle",
  "Trainwreck",
  "Two Worlds Collide",
  "Until You're Mine",
  
  // Here We Go Again (2009)
  "Catch Me",
  "Every Time You Lie",
  "Everything You're Not",
  "Falling Over Me",
  "Gift of a Friend",
  "Got Dynamite",
  "Here We Go Again",
  "Quiet",
  "Remember December",
  "So Far So Great",
  "Solo",
  "Stop The World",
  "U Got Nothin' On Me",
  "World Of Chances",
  
  // Unbroken (2011)
  "All Night Long",
  "Fix a Heart",
  "For the Love of a Daughter",
  "Give Your Heart a Break",
  "Hold Up",
  "In Real Life",
  "Lightweight",
  "Mistake",
  "My Love Is Like a Star",
  "Skyscraper",
  "Together",
  "Unbroken",
  "Who's That Boy",
  "You're My Only Shorty",
  
  // Demi (2013)
  "Something That We're Not",
  "Fire Starter",
  "Heart Attack",
  "I Hate You, Don't Leave Me",
  "In Case",
  "Made In The USA",
  "Neon Lights",
  "Never Been Hurt",
  "Nightingale",
  "Really Don't Care",
  "Shouldn't Come Back",
  "Two Pieces",
  "Warrior",
  "Without The Love",
  
  // Confident (2015)
  "Confident",
  "Cool for the Summer",
  "Father",
  "For You",
  "Kingdom Come",
  "Lionheart",
  "Mr. Hughes",
  "Old Ways",
  "Stars",
  "Stone Cold",
  "Waitin for You",
  "Wildfire",
  "Yes",
  
  // Tell Me You Love Me (2017)
  "Concentrate",
  "Cry Baby",
  "Daddy Issues",
  "Games",
  "Hitchhiker",
  "Instruction",
  "Lonely",
  "Only Forever",
  "Ready For Ya",
  "Ruin The Friendship",
  "Sexy Dirty Love",
  "Smoke & Mirrors",
  "Sober",
  "Sorry Not Sorry",
  "Tell Me You Love Me",
  "You Don't Do It For Me Anymore",
  
  // Dancing With The Devil... The Art Of Starting Over (2021) - DWTD
  "15 Minutes",
  "Anyone",
  "Butterfly",
  "California Sober",
  "Carefully",
  "Dancing With The Devil",
  "Easy",
  "Good Place",
  "I Love Me",
  "I'm Ready",
  "ICU",
  "Intro",
  "Lonely People",
  "Mad World",
  "Melon Cake",
  "Met Him Last Night",
  "My Girlfriends Are My Boyfriend",
  "OK Not To Be OK",
  "Sunset",
  "The Art Of Starting Over",
  "The Kind Of Lover I Am",
  "The Way You Don't Look At Me",
  "What Other People Say",
  
  // HOLY FVCK (2022)
  "29",
  "4 EVER 4 ME",
  "BONES",
  "CITY OF ANGELS",
  "COME TOGETHER",
  "DEAD FRIENDS",
  "EAT ME",
  "FEED",
  "FREAK",
  "HAPPY ENDING",
  "HEAVEN",
  "HELP ME",
  "SKIN OF MY TEETH",
  "SUBSTANCE",
  "WASTED",
  
  // I'm In The Dark (2023) - INTD
  "Before I Knew You",
  "Fast",
  "Frequency",
  "Ghost",
  "Here All Night",
  "In My Head",
  "Joshua Tree",
  "Kiss",
  "Let You Go",
  "Little Bit",
  "Say It",
  "Sorry To Myself"
];

// Album mapping for Demi Lovato songs
// Image files in album bucket: hwga.jpg, dontforget.jpg, unbroken.jpg, demi.jpg, confident.jpg, tmylm.jpg, dwtd.jpg, holyfvck.jpg, intd.jpg
export const demiAlbumMap = {
  // Don't Forget (2008)
  "Believe In Me": "dontforget",
  "Don't Forget": "dontforget",
  "Get Back": "dontforget",
  "Gonna Get Caught": "dontforget",
  "La La Land": "dontforget",
  "On the Line": "dontforget",
  "Party": "dontforget",
  "The Middle": "dontforget",
  "Trainwreck": "dontforget",
  "Two Worlds Collide": "dontforget",
  "Until You're Mine": "dontforget",
  
  // Here We Go Again (2009)
  "Catch Me": "hwga",
  "Every Time You Lie": "hwga",
  "Everything You're Not": "hwga",
  "Falling Over Me": "hwga",
  "Gift of a Friend": "hwga",
  "Got Dynamite": "hwga",
  "Here We Go Again": "hwga",
  "Quiet": "hwga",
  "Remember December": "hwga",
  "So Far So Great": "hwga",
  "Solo": "hwga",
  "Stop The World": "hwga",
  "U Got Nothin' On Me": "hwga",
  "World Of Chances": "hwga",
  
  // Unbroken (2011)
  "All Night Long": "unbroken",
  "Fix a Heart": "unbroken",
  "For the Love of a Daughter": "unbroken",
  "Give Your Heart a Break": "unbroken",
  "Hold Up": "unbroken",
  "In Real Life": "unbroken",
  "Lightweight": "unbroken",
  "Mistake": "unbroken",
  "My Love Is Like a Star": "unbroken",
  "Skyscraper": "unbroken",
  "Together": "unbroken",
  "Unbroken": "unbroken",
  "Who's That Boy": "unbroken",
  "You're My Only Shorty": "unbroken",
  
  // Demi (2013)
  "Something That We're Not": "demi",
  "Fire Starter": "demi",
  "Heart Attack": "demi",
  "I Hate You, Don't Leave Me": "demi",
  "In Case": "demi",
  "Made In The USA": "demi",
  "Neon Lights": "demi",
  "Never Been Hurt": "demi",
  "Nightingale": "demi",
  "Really Don't Care": "demi",
  "Shouldn't Come Back": "demi",
  "Two Pieces": "demi",
  "Warrior": "demi",
  "Without The Love": "demi",
  
  // Confident (2015)
  "Confident": "confident",
  "Cool for the Summer": "confident",
  "Father": "confident",
  "For You": "confident",
  "Kingdom Come": "confident",
  "Lionheart": "confident",
  "Mr. Hughes": "confident",
  "Old Ways": "confident",
  "Stars": "confident",
  "Stone Cold": "confident",
  "Waitin for You": "confident",
  "Wildfire": "confident",
  "Yes": "confident",
  
  // Tell Me You Love Me (2017)
  "Concentrate": "tmylm",
  "Cry Baby": "tmylm",
  "Daddy Issues": "tmylm",
  "Games": "tmylm",
  "Hitchhiker": "tmylm",
  "Instruction": "tmylm",
  "Lonely": "tmylm",
  "Only Forever": "tmylm",
  "Ready For Ya": "tmylm",
  "Ruin The Friendship": "tmylm",
  "Sexy Dirty Love": "tmylm",
  "Smoke & Mirrors": "tmylm",
  "Sober": "tmylm",
  "Sorry Not Sorry": "tmylm",
  "Tell Me You Love Me": "tmylm",
  "You Don't Do It For Me Anymore": "tmylm",
  
  // Dancing With The Devil... The Art Of Starting Over (2021)
  "15 Minutes": "dwtd",
  "Anyone": "dwtd",
  "Butterfly": "dwtd",
  "California Sober": "dwtd",
  "Carefully": "dwtd",
  "Dancing With The Devil": "dwtd",
  "Easy": "dwtd",
  "Good Place": "dwtd",
  "I Love Me": "dwtd",
  "I'm Ready": "dwtd",
  "ICU": "dwtd",
  "Intro": "dwtd",
  "Lonely People": "dwtd",
  "Mad World": "dwtd",
  "Melon Cake": "dwtd",
  "Met Him Last Night": "dwtd",
  "My Girlfriends Are My Boyfriend": "dwtd",
  "OK Not To Be OK": "dwtd",
  "Sunset": "dwtd",
  "The Art Of Starting Over": "dwtd",
  "The Kind Of Lover I Am": "dwtd",
  "The Way You Don't Look At Me": "dwtd",
  "What Other People Say": "dwtd",
  
  // HOLY FVCK (2022)
  "29": "holyfvck",
  "4 EVER 4 ME": "holyfvck",
  "BONES": "holyfvck",
  "CITY OF ANGELS": "holyfvck",
  "COME TOGETHER": "holyfvck",
  "DEAD FRIENDS": "holyfvck",
  "EAT ME": "holyfvck",
  "FEED": "holyfvck",
  "FREAK": "holyfvck",
  "HAPPY ENDING": "holyfvck",
  "HEAVEN": "holyfvck",
  "HELP ME": "holyfvck",
  "SKIN OF MY TEETH": "holyfvck",
  "SUBSTANCE": "holyfvck",
  "WASTED": "holyfvck",
  
  // I'm In The Dark (2023)
  "Before I Knew You": "intd",
  "Fast": "intd",
  "Frequency": "intd",
  "Ghost": "intd",
  "Here All Night": "intd",
  "In My Head": "intd",
  "Joshua Tree": "intd",
  "Kiss": "intd",
  "Let You Go": "intd",
  "Little Bit": "intd",
  "Say It": "intd",
  "Sorry To Myself": "intd"
};
