// Drake song list and album mappings

export const drakeSongs = [

  // Care Package
  "4PM In Calabasas",
  "5 Am in Toronto",
  "How Bout Now",
  "Jodeci Freestyle",
  "The Motion (feat. Sampha)",

  // Certified Lover Boy
  "Champagne Poetry",
  "Fair Trade ft. Travis Scott",
  "Girls Want Girls ft. Lil Baby",
  "IMY2 ft. Kid Cudi",
  "In The Bible ft. Lil Durk & Giveon",
  "Knife Talk ft. 21 Savage & Project Pat",
  "Love All ft. Jay-Z",
  "No Friends In The Industry",
  "Papi's Home",
  "Pipe Down",
  "TSU",
  "The Remorse",
  "Way 2 Sexy ft. Future & Young Thug",
  "Yebbas Heartbreak ft. Yebba",
  "You Only Live Twice ft. Lil Wayne & Rick Ross",

  // Dark Lane Demo Tapes
  "Chicago Freestyle ft. Giveon",
  "Demons ft. Fivio Foreign, Sosa Geek",
  "Desires ft. Future",
  "From Florida With Love",
  "Landed",
  "Pain 1993 ft. Playboi Carti",
  "Time Flies",
  "Toosie Slide",
  "War",
  "D4L",

  // For All The Dogs
  "8am in Charlotte",
  "All The Parties",
  "Away From Home",
  "Bahamas Promises",
  "Calling For You",
  "Daylight",
  "Drew A Picasso",
  "Fear Of Heights",
  "First Person Shooter",
  "IDGAF",
  "Members Only",
  "Polar Opposites",
  "Rich Baby Daddy",
  "Slime You Out",
  "Tried Our Best",
  "Virginia Beach",
  "What Would Pluto Do",

  // Honestly Nevermind
  "Jimmy Cooks",
  "Sticky",

  // If Youre Reading This Its Too Late
  "10 Bands",
  "6 God",
  "6 Man",
  "6PM In New York",
  "Company",
  "Energy",
  "Jungle",
  "Know Yourself",
  "Legend",
  "No Tellin'",
  "Now & Forever",
  "Preach",
  "Star67",
  "Used To",

  // More Life
  "4422",
  "Blem",
  "Can't Have Everything",
  "Do Not Disturb",
  "Fake Love",
  "Free Smoke",
  "Get It Together",
  "Glow",
  "Gyalchester",
  "Ice Melts",
  "Jorja Interlude",
  "KMT",
  "Lose You",
  "Madiba Riddim",
  "No Long Talk",
  "Nothings Into Somethings",
  "Passionfruit",
  "Portland",
  "Sacrifices",
  "Since Way Back",
  "Skepta Interlude",
  "Teenage Fever",

  // Nothing Was The Same
  "All Me",
  "From Time",
  "Furthest Thing",
  "Hold On, We're Going Home (Album Version)",
  "Own It",
  "Pound Cake Paris Morton Music 2",
  "Started From the Bottom (Explicit Version)",
  "Too Much",
  "Tuscan Leather",
  "Worst Behavior",
  "Wu-Tang Forever",

  // Other
  "Lemon Pepper Freestyle",
  "Money In The Grave",
  "Stories About My Brother",
  "The Shoe Fits",
  "Wants and Needs",
  "What's Next",
  "You Broke My Heart",

  // Scorpion
  "8 Out Of 10",
  "Blue Tint",
  "Cant Take A Joke",
  "Dont Matter To Me",
  "Elevate",
  "Emotionless",
  "God's Plan",
  "I'm Upset",
  "In My Feelings",
  "Mob Ties",
  "Nice For What",
  "Nonstop",
  "Summer Games",
  "Survival",
  "Talk Up",
  "Thats How You Feel",

  // So Far Gone
  "A Night Off",
  "Best I Ever Had",
  "Brand New",
  "Bria's Interlude",
  "Houstatlantavegas",
  "Ignant Shit",
  "Lets Call It Off",
  "Little Bit",
  "Lust For Life",
  "November 18th",
  "Outro",
  "Say Whats Real",
  "Sooner Than Later",
  "Successful",
  "The Calm",
  "Unstoppable",
  "Uptown",

  // Take Care
  "Crew Love",
  "HYFR (Hell Ya Fucking Right)",
  "Headlines (Explicit)",
  "Lord Knows",
  "Marvins Room",
  "Over My Dead Body",
  "Practice",
  "Take Care",
  "The Ride",
  "Under Ground Kings",
  "We'll Be Fine",

  // Thank Me Later
  "Fireworks (feat. Alicia Keys)",
  "Karaoke",
  "The Resistance",
  "Over",
  "Show Me A Good Time",
  "Up All Night (feat. Nicki Minaj)",
  "Fancy (feat. T.I. & Swizz Beatz)",
  "Shut It Down (feat. The-Dream)",
  "Unforgettable (feat. Young Jeezy)",
  "Light Up (feat. Jay-Z)",
  "Miss Me (feat. Lil Wayne)",
  "Cece's Interlude",
  "Find Your Love",
  "Thank Me Now",
  "Best I Ever Had (Bonus Track)",
  "Successful (feat. Trey Songz & Lil Wayne) (Bonus Track)",
  "Uptown (feat. Bun B & Lil Wayne) (Bonus Track)",
  "9AM In Dallas (Bonus Track)",

  // Views
  "9",
  "Childs Play",
  "Controlla",
  "Feel No Ways",
  "Fire & Desire",
  "Grammys ft. Future",
  "Hotline Bling",
  "Hype",
  "One Dance ft. Wizkid & Kyla",
  "Pop Style",
  "Redemption",
  "Still Here",
  "Too Good",
  "U With Me",
  "Views",
  "Weston Road Flows",
  "With You ft. PARTYNEXTDOOR",

];

// Album mapping for Drake songs
// Image files in Supabase: sfg.jpg, tml.jpg, takecare.jpg, nwts.jpg, iyrtitl.jpg, views.jpg, morelife.jpg, scorpion.jpg, darklane.jpg, clb.jpg, hnm.jpg, herloss.jpg, fad.jpg, carepackage.jpg, drake.jpg

export const drakeAlbumMap = {

  "4PM In Calabasas": "carepackage",
  "5 Am in Toronto": "carepackage",
  "How Bout Now": "carepackage",
  "Jodeci Freestyle": "carepackage",
  "The Motion (feat. Sampha)": "carepackage",
  "Champagne Poetry": "clb",
  "Fair Trade ft. Travis Scott": "clb",
  "Girls Want Girls ft. Lil Baby": "clb",
  "IMY2 ft. Kid Cudi": "clb",
  "In The Bible ft. Lil Durk & Giveon": "clb",
  "Knife Talk ft. 21 Savage & Project Pat": "clb",
  "Love All ft. Jay-Z": "clb",
  "No Friends In The Industry": "clb",
  "Papi's Home": "clb",
  "Pipe Down": "clb",
  "TSU": "clb",
  "The Remorse": "clb",
  "Way 2 Sexy ft. Future & Young Thug": "clb",
  "Yebbas Heartbreak ft. Yebba": "clb",
  "You Only Live Twice ft. Lil Wayne & Rick Ross": "clb",
  "Chicago Freestyle ft. Giveon": "darklane",
  "Demons ft. Fivio Foreign, Sosa Geek": "darklane",
  "Desires ft. Future": "darklane",
  "From Florida With Love": "darklane",
  "Landed": "darklane",
  "Pain 1993 ft. Playboi Carti": "darklane",
  "Time Flies": "darklane",
  "Toosie Slide": "darklane",
  "War": "darklane",
  "D4L": "darklane",
  "8am in Charlotte": "fad",
  "All The Parties": "fad",
  "Away From Home": "fad",
  "Bahamas Promises": "fad",
  "Calling For You": "fad",
  "Daylight": "fad",
  "Drew A Picasso": "fad",
  "Fear Of Heights": "fad",
  "First Person Shooter": "fad",
  "IDGAF": "fad",
  "Members Only": "fad",
  "Polar Opposites": "fad",
  "Rich Baby Daddy": "fad",
  "Slime You Out": "fad",
  "Tried Our Best": "fad",
  "Virginia Beach": "fad",
  "What Would Pluto Do": "fad",
  "Jimmy Cooks": "hnm",
  "Sticky": "hnm",
  "10 Bands": "iyrtitl",
  "6 God": "iyrtitl",
  "6 Man": "iyrtitl",
  "6PM In New York": "iyrtitl",
  "Company": "iyrtitl",
  "Energy": "iyrtitl",
  "Jungle": "iyrtitl",
  "Know Yourself": "iyrtitl",
  "Legend": "iyrtitl",
  "No Tellin'": "iyrtitl",
  "Now & Forever": "iyrtitl",
  "Preach": "iyrtitl",
  "Star67": "iyrtitl",
  "Used To": "iyrtitl",
  "4422": "morelife",
  "Blem": "morelife",
  "Can't Have Everything": "morelife",
  "Do Not Disturb": "morelife",
  "Fake Love": "morelife",
  "Free Smoke": "morelife",
  "Get It Together": "morelife",
  "Glow": "morelife",
  "Gyalchester": "morelife",
  "Ice Melts": "morelife",
  "Jorja Interlude": "morelife",
  "KMT": "morelife",
  "Lose You": "morelife",
  "Madiba Riddim": "morelife",
  "No Long Talk": "morelife",
  "Nothings Into Somethings": "morelife",
  "Passionfruit": "morelife",
  "Portland": "morelife",
  "Sacrifices": "morelife",
  "Since Way Back": "morelife",
  "Skepta Interlude": "morelife",
  "Teenage Fever": "morelife",
  "All Me": "nwts",
  "From Time": "nwts",
  "Furthest Thing": "nwts",
  "Hold On, We're Going Home (Album Version)": "nwts",
  "Own It": "nwts",
  "Pound Cake Paris Morton Music 2": "nwts",
  "Started From the Bottom (Explicit Version)": "nwts",
  "Too Much": "nwts",
  "Tuscan Leather": "nwts",
  "Worst Behavior": "nwts",
  "Wu-Tang Forever": "nwts",
  "Lemon Pepper Freestyle": "drake",
  "Money In The Grave": "drake",
  "Stories About My Brother": "drake",
  "The Shoe Fits": "drake",
  "Wants and Needs": "drake",
  "What's Next": "drake",
  "You Broke My Heart": "drake",
  "8 Out Of 10": "scorpion",
  "Blue Tint": "scorpion",
  "Cant Take A Joke": "scorpion",
  "Dont Matter To Me": "scorpion",
  "Elevate": "scorpion",
  "Emotionless": "scorpion",
  "God's Plan": "scorpion",
  "I'm Upset": "scorpion",
  "In My Feelings": "scorpion",
  "Mob Ties": "scorpion",
  "Nice For What": "scorpion",
  "Nonstop": "scorpion",
  "Summer Games": "scorpion",
  "Survival": "scorpion",
  "Talk Up": "scorpion",
  "Thats How You Feel": "scorpion",
  "A Night Off": "sfg",
  "Best I Ever Had": "sfg",
  "Brand New": "sfg",
  "Bria's Interlude": "sfg",
  "Houstatlantavegas": "sfg",
  "Ignant Shit": "sfg",
  "Lets Call It Off": "sfg",
  "Little Bit": "sfg",
  "Lust For Life": "sfg",
  "November 18th": "sfg",
  "Outro": "sfg",
  "Say Whats Real": "sfg",
  "Sooner Than Later": "sfg",
  "Successful": "sfg",
  "The Calm": "sfg",
  "Unstoppable": "sfg",
  "Uptown": "sfg",
  "Crew Love": "takecare",
  "HYFR (Hell Ya Fucking Right)": "takecare",
  "Headlines (Explicit)": "takecare",
  "Lord Knows": "takecare",
  "Marvins Room": "takecare",
  "Over My Dead Body": "takecare",
  "Practice": "takecare",
  "Take Care": "takecare",
  "The Ride": "takecare",
  "Under Ground Kings": "takecare",
  "We'll Be Fine": "takecare",
  "Fireworks (feat. Alicia Keys)": "tml",
  "Karaoke": "tml",
  "The Resistance": "tml",
  "Over": "tml",
  "Show Me A Good Time": "tml",
  "Up All Night (feat. Nicki Minaj)": "tml",
  "Fancy (feat. T.I. & Swizz Beatz)": "tml",
  "Shut It Down (feat. The-Dream)": "tml",
  "Unforgettable (feat. Young Jeezy)": "tml",
  "Light Up (feat. Jay-Z)": "tml",
  "Miss Me (feat. Lil Wayne)": "tml",
  "Cece's Interlude": "tml",
  "Find Your Love": "tml",
  "Thank Me Now": "tml",
  "Best I Ever Had (Bonus Track)": "tml",
  "Successful (feat. Trey Songz & Lil Wayne) (Bonus Track)": "tml",
  "Uptown (feat. Bun B & Lil Wayne) (Bonus Track)": "tml",
  "9AM In Dallas (Bonus Track)": "tml",
  "9": "views",
  "Childs Play": "views",
  "Controlla": "views",
  "Feel No Ways": "views",
  "Fire & Desire": "views",
  "Grammys ft. Future": "views",
  "Hotline Bling": "views",
  "Hype": "views",
  "One Dance ft. Wizkid & Kyla": "views",
  "Pop Style": "views",
  "Redemption": "views",
  "Still Here": "views",
  "Too Good": "views",
  "U With Me": "views",
  "Views": "views",
  "Weston Road Flows": "views",
  "With You ft. PARTYNEXTDOOR": "views",
};