// Drake song list and album mappings

export const drakeSongs = [

  // Care Package
  "4PM In Calabasas",
  "5 Am in Toronto",
  "Can I",
  "Club Paradise",
  "Days in The East",
  "Draft Day",
  "Dreams Money Can Buy",
  "Free Spirit",
  "Girls Love Beyonce",
  "Heat Of The Moment",
  "How Bout Now",
  "I Get Lonely",
  "Jodeci Freestyle",
  "My Side",
  "Paris Morton Music",
  "The Motion",
  "The Motion (feat. Sampha)",
  "Trust Issues",
  "Trust Issues (Remix)",

  // Certified Lover Boy
  "7am On Bridle Path",
  "Champagne Poetry",
  "Fair Trade ft. Travis Scott",
  "Fountains ft. Tems",
  "Fcking Fans",
  "Get Along Better ft. Ty Dolla $ign",
  "Girls Want Girls ft. Lil Baby",
  "IMY2 ft. Kid Cudi",
  "In The Bible ft. Lil Durk & Giveon",
  "Knife Talk ft. 21 Savage & Project Pat",
  "Love All ft. Jay-Z",
  "N 2 Deep ft. Future",
  "No Friends In The Industry",
  "Papi's Home",
  "Pipe Down",
  "Race My Mind",
  "TSU",
  "The Remorse",
  "Way 2 Sexy ft. Future & Young Thug",
  "Yebbas Heartbreak ft. Yebba",
  "You Only Live Twice ft. Lil Wayne & Rick Ross",

  // Dark Lane Demo Tapes
  "Chicago Freestyle ft. Giveon",
  "Deep Pockets",
  "Demons ft. Fivio Foreign, Sosa Geek",
  "Desires ft. Future",
  "From Florida With Love",
  "Landed",
  "Losses",
  "Not You Too ft. Chris Brown",
  "Pain 1993 ft. Playboi Carti",
  "Time Flies",
  "Toosie Slide",
  "War",
  "When To Say When",
  "D4L",

  // For All The Dogs
  "7969 Santa",
  "8am in Charlotte",
  "All The Parties",
  "Amen",
  "Another Late Night",
  "Away From Home",
  "BBL Love (Interlude)",
  "Bahamas Promises",
  "Calling For You",
  "Daylight",
  "Drew A Picasso",
  "Fear Of Heights",
  "First Person Shooter",
  "Gently",
  "IDGAF",
  "Members Only",
  "Polar Opposites",
  "Rich Baby Daddy",
  "Screw The World (Interlude)",
  "Slime You Out",
  "Tried Our Best",
  "Virginia Beach",
  "What Would Pluto Do",

  // Honestly Nevermind
  "A Keeper",
  "Calling My Name",
  "Currents",
  "Down Hill",
  "Falling Back",
  "Flight's Booked",
  "Jimmy Cooks",
  "Liability",
  "Massive",
  "Overdrive",
  "Sticky",
  "Texts Go Green",
  "Tie That Binds",

  // If Youre Reading This Its Too Late
  "10 Bands",
  "6 God",
  "6 Man",
  "6PM In New York",
  "Company",
  "Energy",
  "Jungle",
  "Know Yourself",
  "Legend",
  "Madonna",
  "No Tellin'",
  "Now & Forever",
  "Preach",
  "Star67",
  "Used To",
  "Wednesday Night Interlude",
  "You & The 6",

  // More Life
  "4422",
  "Blem",
  "Can't Have Everything",
  "Do Not Disturb",
  "Fake Love",
  "Free Smoke",
  "Get It Together",
  "Glow",
  "Gyalchester",
  "Ice Melts",
  "Jorja Interlude",
  "KMT",
  "Lose You",
  "Madiba Riddim",
  "No Long Talk",
  "Nothings Into Somethings",
  "Passionfruit",
  "Portland",
  "Sacrifices",
  "Since Way Back",
  "Skepta Interlude",
  "Teenage Fever",

  // Nothing Was The Same
  "305 To My City",
  "All Me",
  "Come Thru",
  "Connect",
  "From Time",
  "Furthest Thing",
  "Hold On, We're Going Home (Album Version)",
  "Own It",
  "Pound Cake Paris Morton Music 2",
  "Started From the Bottom (Explicit Version)",
  "The Language",
  "The Motion",
  "Too Much",
  "Tuscan Leather",
  "Worst Behavior",
  "Wu-Tang Forever",

  // Other
  "Diplomatic Immunity",
  "Evil Ways",
  "Lemon Pepper Freestyle",
  "Money In The Grave",
  "Omerta",
  "Red Button",
  "Stories About My Brother",
  "The Shoe Fits",
  "Wants and Needs",
  "What's Next",
  "Wick Man",
  "You Broke My Heart",

  // Scorpion
  "8 Out Of 10",
  "After Dark",
  "Blue Tint",
  "Cant Take A Joke",
  "Dont Matter To Me",
  "Elevate",
  "Emotionless",
  "Final Fantasy",
  "Finesse",
  "God's Plan",
  "I'm Upset",
  "In My Feelings",
  "Is There More",
  "Jaded",
  "March 14",
  "Mob Ties",
  "Nice For What",
  "Nonstop",
  "Peak",
  "Ratchet Happy Birthday",
  "Sandras Rose",
  "Summer Games",
  "Survival",
  "Talk Up",
  "Thats How You Feel",

  // So Far Gone
  "A Night Off",
  "Best I Ever Had",
  "Brand New",
  "Bria's Interlude",
  "Houstatlantavegas",
  "Ignant Shit",
  "Lets Call It Off",
  "Little Bit",
  "Lust For Life",
  "November 18th",
  "Outro",
  "Say Whats Real",
  "Sooner Than Later",
  "Successful",
  "The Calm",
  "Unstoppable",
  "Uptown",

  // Take Care
  "Cameras Good Ones Go Interlude (Medley)",
  "Crew Love",
  "Doing It Wrong",
  "HYFR (Hell Ya Fucking Right)",
  "Headlines (Explicit)",
  "Look What You've Done",
  "Lord Knows",
  "Make Me Proud",
  "Marvins Room",
  "Over My Dead Body",
  "Practice",
  "Shot For Me",
  "Take Care",
  "The Real Her",
  "The Ride",
  "Under Ground Kings",
  "We'll Be Fine",

  // Thank Me Later
  "Fireworks (feat. Alicia Keys)",
  "Karaoke",
  "The Resistance",
  "Over",
  "Show Me A Good Time",
  "Up All Night (feat. Nicki Minaj)",
  "Fancy (feat. T.I. & Swizz Beatz)",
  "Shut It Down (feat. The-Dream)",
  "Unforgettable (feat. Young Jeezy)",
  "Light Up (feat. Jay-Z)",
  "Miss Me (feat. Lil Wayne)",
  "Cece's Interlude",
  "Find Your Love",
  "Thank Me Now",
  "Best I Ever Had (Bonus Track)",
  "Successful (feat. Trey Songz & Lil Wayne) (Bonus Track)",
  "Uptown (feat. Bun B & Lil Wayne) (Bonus Track)",
  "9AM In Dallas (Bonus Track)",

  // Views
  "9",
  "Childs Play",
  "Controlla",
  "Faithful ft. Pimp C & dvsn",
  "Feel No Ways",
  "Fire & Desire",
  "Grammys ft. Future",
  "Hotline Bling",
  "Hype",
  "Keep the Family Close",
  "One Dance ft. Wizkid & Kyla",
  "Pop Style",
  "Redemption",
  "Still Here",
  "Too Good",
  "U With Me",
  "Views",
  "Weston Road Flows",
  "With You ft. PARTYNEXTDOOR",

];

// Album mapping for Drake songs
// Image files in Supabase: sfg.jpg, tml.jpg, takecare.jpg, nwts.jpg, iyrtitl.jpg, views.jpg, morelife.jpg, scorpion.jpg, darklane.jpg, clb.jpg, hnm.jpg, herloss.jpg, fad.jpg, carepackage.jpg, drake.jpg

export const drakeAlbumMap = {

  "4PM In Calabasas": "carepackage",
  "5 Am in Toronto": "carepackage",
  "Can I": "carepackage",
  "Club Paradise": "carepackage",
  "Days in The East": "carepackage",
  "Draft Day": "carepackage",
  "Dreams Money Can Buy": "carepackage",
  "Free Spirit": "carepackage",
  "Girls Love Beyonce": "carepackage",
  "Heat Of The Moment": "carepackage",
  "How Bout Now": "carepackage",
  "I Get Lonely": "carepackage",
  "Jodeci Freestyle": "carepackage",
  "My Side": "carepackage",
  "Paris Morton Music": "carepackage",
  "The Motion": "carepackage",
  "The Motion (feat. Sampha)": "carepackage",
  "Trust Issues": "carepackage",
  "Trust Issues (Remix)": "carepackage",
  "7am On Bridle Path": "clb",
  "Champagne Poetry": "clb",
  "Fair Trade ft. Travis Scott": "clb",
  "Fountains ft. Tems": "clb",
  "Fcking Fans": "clb",
  "Get Along Better ft. Ty Dolla $ign": "clb",
  "Girls Want Girls ft. Lil Baby": "clb",
  "IMY2 ft. Kid Cudi": "clb",
  "In The Bible ft. Lil Durk & Giveon": "clb",
  "Knife Talk ft. 21 Savage & Project Pat": "clb",
  "Love All ft. Jay-Z": "clb",
  "N 2 Deep ft. Future": "clb",
  "No Friends In The Industry": "clb",
  "Papi's Home": "clb",
  "Pipe Down": "clb",
  "Race My Mind": "clb",
  "TSU": "clb",
  "The Remorse": "clb",
  "Way 2 Sexy ft. Future & Young Thug": "clb",
  "Yebbas Heartbreak ft. Yebba": "clb",
  "You Only Live Twice ft. Lil Wayne & Rick Ross": "clb",
  "Chicago Freestyle ft. Giveon": "darklane",
  "Deep Pockets": "darklane",
  "Demons ft. Fivio Foreign, Sosa Geek": "darklane",
  "Desires ft. Future": "darklane",
  "From Florida With Love": "darklane",
  "Landed": "darklane",
  "Losses": "darklane",
  "Not You Too ft. Chris Brown": "darklane",
  "Pain 1993 ft. Playboi Carti": "darklane",
  "Time Flies": "darklane",
  "Toosie Slide": "darklane",
  "War": "darklane",
  "When To Say When": "darklane",
  "D4L": "darklane",
  "7969 Santa": "fad",
  "8am in Charlotte": "fad",
  "All The Parties": "fad",
  "Amen": "fad",
  "Another Late Night": "fad",
  "Away From Home": "fad",
  "BBL Love (Interlude)": "fad",
  "Bahamas Promises": "fad",
  "Calling For You": "fad",
  "Daylight": "fad",
  "Drew A Picasso": "fad",
  "Fear Of Heights": "fad",
  "First Person Shooter": "fad",
  "Gently": "fad",
  "IDGAF": "fad",
  "Members Only": "fad",
  "Polar Opposites": "fad",
  "Rich Baby Daddy": "fad",
  "Screw The World (Interlude)": "fad",
  "Slime You Out": "fad",
  "Tried Our Best": "fad",
  "Virginia Beach": "fad",
  "What Would Pluto Do": "fad",
  "A Keeper": "hnm",
  "Calling My Name": "hnm",
  "Currents": "hnm",
  "Down Hill": "hnm",
  "Falling Back": "hnm",
  "Flight's Booked": "hnm",
  "Jimmy Cooks": "hnm",
  "Liability": "hnm",
  "Massive": "hnm",
  "Overdrive": "hnm",
  "Sticky": "hnm",
  "Texts Go Green": "hnm",
  "Tie That Binds": "hnm",
  "10 Bands": "iyrtitl",
  "6 God": "iyrtitl",
  "6 Man": "iyrtitl",
  "6PM In New York": "iyrtitl",
  "Company": "iyrtitl",
  "Energy": "iyrtitl",
  "Jungle": "iyrtitl",
  "Know Yourself": "iyrtitl",
  "Legend": "iyrtitl",
  "Madonna": "iyrtitl",
  "No Tellin'": "iyrtitl",
  "Now & Forever": "iyrtitl",
  "Preach": "iyrtitl",
  "Star67": "iyrtitl",
  "Used To": "iyrtitl",
  "Wednesday Night Interlude": "iyrtitl",
  "You & The 6": "iyrtitl",
  "4422": "morelife",
  "Blem": "morelife",
  "Can't Have Everything": "morelife",
  "Do Not Disturb": "morelife",
  "Fake Love": "morelife",
  "Free Smoke": "morelife",
  "Get It Together": "morelife",
  "Glow": "morelife",
  "Gyalchester": "morelife",
  "Ice Melts": "morelife",
  "Jorja Interlude": "morelife",
  "KMT": "morelife",
  "Lose You": "morelife",
  "Madiba Riddim": "morelife",
  "No Long Talk": "morelife",
  "Nothings Into Somethings": "morelife",
  "Passionfruit": "morelife",
  "Portland": "morelife",
  "Sacrifices": "morelife",
  "Since Way Back": "morelife",
  "Skepta Interlude": "morelife",
  "Teenage Fever": "morelife",
  "305 To My City": "nwts",
  "All Me": "nwts",
  "Come Thru": "nwts",
  "Connect": "nwts",
  "From Time": "nwts",
  "Furthest Thing": "nwts",
  "Hold On, We're Going Home (Album Version)": "nwts",
  "Own It": "nwts",
  "Pound Cake Paris Morton Music 2": "nwts",
  "Started From the Bottom (Explicit Version)": "nwts",
  "The Language": "nwts",
  "The Motion": "nwts",
  "Too Much": "nwts",
  "Tuscan Leather": "nwts",
  "Worst Behavior": "nwts",
  "Wu-Tang Forever": "nwts",
  "Diplomatic Immunity": "drake",
  "Evil Ways": "drake",
  "Lemon Pepper Freestyle": "drake",
  "Money In The Grave": "drake",
  "Omerta": "drake",
  "Red Button": "drake",
  "Stories About My Brother": "drake",
  "The Shoe Fits": "drake",
  "Wants and Needs": "drake",
  "What's Next": "drake",
  "Wick Man": "drake",
  "You Broke My Heart": "drake",
  "8 Out Of 10": "scorpion",
  "After Dark": "scorpion",
  "Blue Tint": "scorpion",
  "Cant Take A Joke": "scorpion",
  "Dont Matter To Me": "scorpion",
  "Elevate": "scorpion",
  "Emotionless": "scorpion",
  "Final Fantasy": "scorpion",
  "Finesse": "scorpion",
  "God's Plan": "scorpion",
  "I'm Upset": "scorpion",
  "In My Feelings": "scorpion",
  "Is There More": "scorpion",
  "Jaded": "scorpion",
  "March 14": "scorpion",
  "Mob Ties": "scorpion",
  "Nice For What": "scorpion",
  "Nonstop": "scorpion",
  "Peak": "scorpion",
  "Ratchet Happy Birthday": "scorpion",
  "Sandras Rose": "scorpion",
  "Summer Games": "scorpion",
  "Survival": "scorpion",
  "Talk Up": "scorpion",
  "Thats How You Feel": "scorpion",
  "A Night Off": "sfg",
  "Best I Ever Had": "sfg",
  "Brand New": "sfg",
  "Bria's Interlude": "sfg",
  "Houstatlantavegas": "sfg",
  "Ignant Shit": "sfg",
  "Lets Call It Off": "sfg",
  "Little Bit": "sfg",
  "Lust For Life": "sfg",
  "November 18th": "sfg",
  "Outro": "sfg",
  "Say Whats Real": "sfg",
  "Sooner Than Later": "sfg",
  "Successful": "sfg",
  "The Calm": "sfg",
  "Unstoppable": "sfg",
  "Uptown": "sfg",
  "Cameras Good Ones Go Interlude (Medley)": "takecare",
  "Crew Love": "takecare",
  "Doing It Wrong": "takecare",
  "HYFR (Hell Ya Fucking Right)": "takecare",
  "Headlines (Explicit)": "takecare",
  "Look What You've Done": "takecare",
  "Lord Knows": "takecare",
  "Make Me Proud": "takecare",
  "Marvins Room": "takecare",
  "Over My Dead Body": "takecare",
  "Practice": "takecare",
  "Shot For Me": "takecare",
  "Take Care": "takecare",
  "The Real Her": "takecare",
  "The Ride": "takecare",
  "Under Ground Kings": "takecare",
  "We'll Be Fine": "takecare",
  "Fireworks (feat. Alicia Keys)": "tml",
  "Karaoke": "tml",
  "The Resistance": "tml",
  "Over": "tml",
  "Show Me A Good Time": "tml",
  "Up All Night (feat. Nicki Minaj)": "tml",
  "Fancy (feat. T.I. & Swizz Beatz)": "tml",
  "Shut It Down (feat. The-Dream)": "tml",
  "Unforgettable (feat. Young Jeezy)": "tml",
  "Light Up (feat. Jay-Z)": "tml",
  "Miss Me (feat. Lil Wayne)": "tml",
  "Cece's Interlude": "tml",
  "Find Your Love": "tml",
  "Thank Me Now": "tml",
  "Best I Ever Had (Bonus Track)": "tml",
  "Successful (feat. Trey Songz & Lil Wayne) (Bonus Track)": "tml",
  "Uptown (feat. Bun B & Lil Wayne) (Bonus Track)": "tml",
  "9AM In Dallas (Bonus Track)": "tml",
  "9": "views",
  "Childs Play": "views",
  "Controlla": "views",
  "Faithful ft. Pimp C & dvsn": "views",
  "Feel No Ways": "views",
  "Fire & Desire": "views",
  "Grammys ft. Future": "views",
  "Hotline Bling": "views",
  "Hype": "views",
  "Keep the Family Close": "views",
  "One Dance ft. Wizkid & Kyla": "views",
  "Pop Style": "views",
  "Redemption": "views",
  "Still Here": "views",
  "Too Good": "views",
  "U With Me": "views",
  "Views": "views",
  "Weston Road Flows": "views",
  "With You ft. PARTYNEXTDOOR": "views",
};