// J. Cole song list and album mappings
// Album names match the image files in Supabase albums bucket

export const jcoleSongs = [
  // 2014 Forest Hills Drive
  "January 28th",
  "Wet Dreamz",
  "03' Adolescence",
  "A Tale of 2 Citiez",
  "Fire Squad",
  "St. Tropez",
  "G.O.M.D.",
  "No Role Modelz",
  "Hello",
  "Apparently",
  "Love Yourz",
  "Note to Self",
  
  // 4 Your Eyez Only
  "For Whom the Bell Tolls",
  "Immortal",
  "Deja Vu",
  "Ville Mentality",
  "She's Mine Pt. 1",
  "Change",
  "Neighbors",
  "Foldin Clothes",
  "She's Mine Pt. 2",
  "4 Your Eyez Only",
  
  // Born Sinner
  "Villuminati",
  "Kerney Sermon (Skit)",
  "LAnd of the Snakes",
  "Power Trip (feat. Miguel)",
  "Mo Money (Interlude)",
  "Trouble",
  "Runaway",
  "She Knows (feat. Amber Coffman & Cults)",
  "Rich Niggaz",
  "Where's Jermaine (Skit)",
  "Forbidden Fruit (feat. Kendrick Lamar)",
  "Chaining Day",
  "Ain't That Some Shit (Interlude)",
  "Crooked Smile (feat. TLC)",
  "Let Nas Down",
  "Born Sinner (feat. @Fauntleroy)",
  "Miss America",
  "New York Times (feat. 50 Cent & Bas)",
  "Is She Gon Pop",
  "Niggaz Know",
  "Sparks Will Fly (feat. Jhene Aiko)",
  
  // Cole World: The Sideline Story
  "Dollar and a Dream III",
  "Can't Get Enough (feat. Trey Songz)",
  "Lights Please",
  "Interlude",
  "Sideline Story",
  "Mr. Nice Watch (feat. Jay-Z)",
  "Cole World",
  "In the Morning (feat. Drake)",
  "Lost Ones",
  "Nobody's Perfect (feat. Missy Elliott)",
  "Never Told",
  "Rise & Shine",
  "God's Gift",
  "Breakdown",
  "Work Out",
  "Who Dat",
  "Daddy's Little Girl",
  
  // Friday Night Lights
  "Friday Night Lights (Intro)",
  "Too Deep for the Intro",
  "Before I'm Gone",
  "Back to the Topic (Freestyle)",
  "You Got It (feat. Wale)",
  "Villematic",
  "Enchanted (feat. Wale)",
  "Blow Up",
  "Higher",
  "In the Morning (feat. Drake)",
  "2Face",
  "The Autograph",
  "Best Friend",
  "Cost Me a Lot",
  "Premeditated Murder",
  "Home for the Holidays",
  "Love Me Not",
  "See World",
  "Farewell",
  "Looking for Trouble (feat. Kanye West, Big Sean, Pusha T & Cyhi Da Prince)",
  
  // KOD
  "KOD",
  "Photograph",
  "The Cut Off (feat. kiLL edward)",
  "ATM",
  "Motiv8",
  "Kevins Heart",
  "BRACKETS",
  "Once an Addict (Interlude)",
  "FRIENDS (feat. kiLL edward)",
  "Window Pain (Outro)",
  "1985 (Intro to The Fall Off)",
  
  // Truly Yours Vol. 1
  "Can I Holla At Ya",
  "Crunch Time",
  "Rise Above",
  "Tears for ODB",
  "Stay (2009)",
  
  // Truly Yours, Vol. 2
  "Cole Summer",
  "Kenny Lofton (feat. Young Jeezy)",
  "Chris Tucker (feat. 2 Chainz)",
  "Head Bussa",
  "Cousins (feat. Bas)",
  "3 Wishes"
];

// Album mapping for J. Cole songs
// Image files in Supabase: foresthills.jpg, foureyez.jpg, bornsinner.jpg, sideline.jpg, fnl.jpg, kod.jpg, trulyyours.jpg, trulyyours2.jpg, warmup.jpg
export const jcoleAlbumMap = {
  // 2014 Forest Hills Drive
  "January 28th": "foresthills",
  "Wet Dreamz": "foresthills",
  "03' Adolescence": "foresthills",
  "A Tale of 2 Citiez": "foresthills",
  "Fire Squad": "foresthills",
  "St. Tropez": "foresthills",
  "G.O.M.D.": "foresthills",
  "No Role Modelz": "foresthills",
  "Hello": "foresthills",
  "Apparently": "foresthills",
  "Love Yourz": "foresthills",
  "Note to Self": "foresthills",
  
  // 4 Your Eyez Only
  "For Whom the Bell Tolls": "foureyez",
  "Immortal": "foureyez",
  "Deja Vu": "foureyez",
  "Ville Mentality": "foureyez",
  "She's Mine Pt. 1": "foureyez",
  "Change": "foureyez",
  "Neighbors": "foureyez",
  "Foldin Clothes": "foureyez",
  "She's Mine Pt. 2": "foureyez",
  "4 Your Eyez Only": "foureyez",
  
  // Born Sinner
  "Villuminati": "bornsinner",
  "Kerney Sermon (Skit)": "bornsinner",
  "LAnd of the Snakes": "bornsinner",
  "Power Trip (feat. Miguel)": "bornsinner",
  "Mo Money (Interlude)": "bornsinner",
  "Trouble": "bornsinner",
  "Runaway": "bornsinner",
  "She Knows (feat. Amber Coffman & Cults)": "bornsinner",
  "Rich Niggaz": "bornsinner",
  "Where's Jermaine (Skit)": "bornsinner",
  "Forbidden Fruit (feat. Kendrick Lamar)": "bornsinner",
  "Chaining Day": "bornsinner",
  "Ain't That Some Shit (Interlude)": "bornsinner",
  "Crooked Smile (feat. TLC)": "bornsinner",
  "Let Nas Down": "bornsinner",
  "Born Sinner (feat. @Fauntleroy)": "bornsinner",
  "Miss America": "bornsinner",
  "New York Times (feat. 50 Cent & Bas)": "bornsinner",
  "Is She Gon Pop": "bornsinner",
  "Niggaz Know": "bornsinner",
  "Sparks Will Fly (feat. Jhene Aiko)": "bornsinner",
  
  // Cole World: The Sideline Story
  "Dollar and a Dream III": "sideline",
  "Can't Get Enough (feat. Trey Songz)": "sideline",
  "Lights Please": "sideline",
  "Interlude": "sideline",
  "Sideline Story": "sideline",
  "Mr. Nice Watch (feat. Jay-Z)": "sideline",
  "Cole World": "sideline",
  "In the Morning (feat. Drake)": "sideline",
  "Lost Ones": "sideline",
  "Nobody's Perfect (feat. Missy Elliott)": "sideline",
  "Never Told": "sideline",
  "Rise & Shine": "sideline",
  "God's Gift": "sideline",
  "Breakdown": "sideline",
  "Work Out": "sideline",
  "Who Dat": "sideline",
  "Daddy's Little Girl": "sideline",
  
  // Friday Night Lights
  "Friday Night Lights (Intro)": "fnl",
  "Too Deep for the Intro": "fnl",
  "Before I'm Gone": "fnl",
  "Back to the Topic (Freestyle)": "fnl",
  "You Got It (feat. Wale)": "fnl",
  "Villematic": "fnl",
  "Enchanted (feat. Wale)": "fnl",
  "Blow Up": "fnl",
  "Higher": "fnl",
  "2Face": "fnl",
  "The Autograph": "fnl",
  "Best Friend": "fnl",
  "Cost Me a Lot": "fnl",
  "Premeditated Murder": "fnl",
  "Home for the Holidays": "fnl",
  "Love Me Not": "fnl",
  "See World": "fnl",
  "Farewell": "fnl",
  "Looking for Trouble (feat. Kanye West, Big Sean, Pusha T & Cyhi Da Prince)": "fnl",
  
  // KOD
  "KOD": "kod",
  "Photograph": "kod",
  "The Cut Off (feat. kiLL edward)": "kod",
  "ATM": "kod",
  "Motiv8": "kod",
  "Kevins Heart": "kod",
  "BRACKETS": "kod",
  "Once an Addict (Interlude)": "kod",
  "FRIENDS (feat. kiLL edward)": "kod",
  "Window Pain (Outro)": "kod",
  "1985 (Intro to The Fall Off)": "kod",
  
  // Truly Yours Vol. 1
  "Can I Holla At Ya": "trulyyours",
  "Crunch Time": "trulyyours",
  "Rise Above": "trulyyours",
  "Tears for ODB": "trulyyours",
  "Stay (2009)": "trulyyours",
  
  // Truly Yours, Vol. 2
  "Cole Summer": "trulyyours2",
  "Kenny Lofton (feat. Young Jeezy)": "trulyyours2",
  "Chris Tucker (feat. 2 Chainz)": "trulyyours2",
  "Head Bussa": "trulyyours2",
  "Cousins (feat. Bas)": "trulyyours2",
  "3 Wishes": "trulyyours2"
};
