// Lil Tecca song list and album mappings
// Album names match the image files in Supabase albums bucket
// Images: wlyt.jpg, virgo.jpg, wlyt2.jpg, tecca.jpg

export const lilteccaSongs = [
  // We Love You Tecca (WLYT)
  "Ransom",
  "Love Me",
  "Shots",
  "Count Me Out",
  "Did It Again",
  "Left, Right",
  "Sidenote",
  "Amigo",
  "Bossanova",
  "Out Of Luck",
  "Phenom",
  "Molly Girl",
  "Senorita",
  "The Score",
  "DUI",
  "Weatherman",
  
  // Virgo World
  "Actin Up",
  "Closest To Heaven",
  "True To The Game ft. Guwop Reign",
  "Our Time",
  "When You Down ft. Lil Durk & Polo G",
  "Take 10",
  "Last Call",
  "Tic Toc",
  "Foreign ft. NAV",
  "Chemistry",
  "Royal Rumble",
  "Level Up",
  "Miss Me",
  "Back It Up",
  "Selection ft. Skrillex & DJ Scheme",
  "Dolly ft. Lil Uzi Vert",
  "Insecurities",
  "No Answers",
  
  // We Love You Tecca 2 (WLYT2)
  "DID THAT",
  "REPEAT IT",
  "YOU DON'T NEED ME NO MORE",
  "NADA",
  "MONEY ON ME",
  "FEE",
  "EVERYWHERE I GO",
  "INVESTIGATION",
  "MY SIDE",
  "CAUTION",
  "WHATEVER",
  "LOT OF ME",
  "ABOUT YOU ft. NAV",
  "BANK TELLER",
  "SEASIDE",
  "SHOOTERS",
  "YOU GOTTA GO DO BETTER",
  "NEVER LEFT",
  "CHOPPA SHOOT THE LOUDEST",
  "NO DISCUSSION",
  
  // Other/Singles
  "All Star ft. Lil Tjay",
  "Dark Thoughts",
  "Favorite Lie",
  "Never Left",
  "Out of Love",
  "Treesha"
];

// Album mapping for Lil Tecca songs
// Image files in Supabase: wlyt.jpg, virgo.jpg, wlyt2.jpg, tecca.jpg
export const lilteccaAlbumMap = {
  // We Love You Tecca (WLYT) - wlyt.jpg
  "Ransom": "wlyt",
  "Love Me": "wlyt",
  "Shots": "wlyt",
  "Count Me Out": "wlyt",
  "Did It Again": "wlyt",
  "Left, Right": "wlyt",
  "Sidenote": "wlyt",
  "Amigo": "wlyt",
  "Bossanova": "wlyt",
  "Out Of Luck": "wlyt",
  "Phenom": "wlyt",
  "Molly Girl": "wlyt",
  "Senorita": "wlyt",
  "The Score": "wlyt",
  "DUI": "wlyt",
  "Weatherman": "wlyt",
  
  // Virgo World - virgo.jpg
  "Actin Up": "virgo",
  "Closest To Heaven": "virgo",
  "True To The Game ft. Guwop Reign": "virgo",
  "Our Time": "virgo",
  "When You Down ft. Lil Durk & Polo G": "virgo",
  "Take 10": "virgo",
  "Last Call": "virgo",
  "Tic Toc": "virgo",
  "Foreign ft. NAV": "virgo",
  "Chemistry": "virgo",
  "Royal Rumble": "virgo",
  "Level Up": "virgo",
  "Miss Me": "virgo",
  "Back It Up": "virgo",
  "Selection ft. Skrillex & DJ Scheme": "virgo",
  "Dolly ft. Lil Uzi Vert": "virgo",
  "Insecurities": "virgo",
  "No Answers": "virgo",
  
  // We Love You Tecca 2 (WLYT2) - wlyt2.jpg
  "DID THAT": "wlyt2",
  "REPEAT IT": "wlyt2",
  "YOU DON'T NEED ME NO MORE": "wlyt2",
  "NADA": "wlyt2",
  "MONEY ON ME": "wlyt2",
  "FEE": "wlyt2",
  "EVERYWHERE I GO": "wlyt2",
  "INVESTIGATION": "wlyt2",
  "MY SIDE": "wlyt2",
  "CAUTION": "wlyt2",
  "WHATEVER": "wlyt2",
  "LOT OF ME": "wlyt2",
  "ABOUT YOU ft. NAV": "wlyt2",
  "BANK TELLER": "wlyt2",
  "SEASIDE": "wlyt2",
  "SHOOTERS": "wlyt2",
  "YOU GOTTA GO DO BETTER": "wlyt2",
  "NEVER LEFT": "wlyt2",
  "CHOPPA SHOOT THE LOUDEST": "wlyt2",
  "NO DISCUSSION": "wlyt2",
  
  // Other/Singles - tecca.jpg
  "All Star ft. Lil Tjay": "tecca",
  "Dark Thoughts": "tecca",
  "Favorite Lie": "tecca",
  "Never Left": "tecca",
  "Out of Love": "tecca",
  "Treesha": "tecca"
};
